## name: evergarden summer lime
## author: comfysage
## license: GPL-3.0
## blurb: a comfy colorscheme for cozy morning coding

[colors.primary]
background = "#d7e1eb"
foreground = "#171c1f"
dim_foreground = "#526469"
bright_foreground = "#171c1f"

[colors.cursor]
text = "#bdcbdb"
cursor = "#a7af70"

[colors.vi_mode_cursor]
text = "#bdcbdb"
cursor = "#a7af70"

[colors.search.matches]
foreground = "#c1866b"
background = "#bdcbdb"

[colors.search.focused_match]
foreground = "#bdcbdb"
background = "#c1866b"

[colors.footer_bar]
foreground = "#63787d"
background = "#bdcbdb"

[colors.hints.start]
foreground = "#bdcbdb"
background = "#bc9c6b"

[colors.hints.end]
foreground = "#bdcbdb"
background = "#526469"

[colors.selection]
text = "#171c1f"
background = "#b4c6cc"

[colors.normal]
black = "#d7e1eb"
red = "#c0696b"
green = "#91ac75"
yellow = "#bc9c6b"
blue = "#8ca0bb"
magenta = "#ca9ebd"
cyan = "#7baa92"
white = "#171c1f"

[colors.bright]
black = "#ced9e0"
red = "#c0696b"
green = "#91ac75"
yellow = "#bc9c6b"
blue = "#8ca0bb"
magenta = "#ca9ebd"
cyan = "#7baa92"
white = "#526469"

[colors.dim]
black = "#d7e1eb"
red = "#c0696b"
green = "#91ac75"
yellow = "#bc9c6b"
blue = "#8ca0bb"
magenta = "#ca9ebd"
cyan = "#7baa92"
white = "#171c1f"
